on:
    release:
        types: [published]
  
jobs:
    pypi-publish:
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/pydexcom
        permissions:
            id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
        steps:
            - uses: actions/checkout@v3
            - name: install?
              run: |
                python -m pip install --upgrade pip
                pip install build setuptools setuptools_scm
            - name: build
              run: python3 -m build

            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                repository-url: https://test.pypi.org/legacy/